# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-11-23 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181123_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Riddle',
            new_name='contact',
        ),
    ]
