# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-11-25 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20181123_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='nebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
            ],
        ),
    ]
