# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20181204_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_job', models.CharField(max_length=255)),
                ('doljnost', models.CharField(max_length=255)),
            ],
        ),
    ]
