# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='adres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.adres'),
        ),
    ]
