# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-04 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20181204_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='adres',
        ),
    ]
