# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_contact_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Adres_street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='job_doljnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doljnost', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='job_place_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_job', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='adres',
        ),
        migrations.DeleteModel(
            name='job',
        ),
    ]
